services:
  - type: web
    name: boltiqtrade-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_api.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false